name: Dependency Review

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  dependency-review:
    uses: chargehound/security-workflows-public/.github/workflows/dependency-review.yml@main
